name: Deploy Spring Boot App to Azure VM

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Copy JAR to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "backend/target/*.jar"
          target: "/home/${{ secrets.AZURE_USER }}/app/myapp.jar"

      - name: Restart Spring Boot App on Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            echo "DB_URL=jdbc:postgresql://localhost:5432/mydb" | sudo tee -a /etc/environment
            echo "DB_USER=postgres" | sudo tee -a /etc/environment
            echo "DB_PASS=superSecret" | sudo tee -a /etc/environment
            sudo systemctl restart myapp
